from datetime import datetime
from io import BytesIO
from xml.sax.saxutils import escape

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Avg, Count, DurationField, ExpressionWrapper, F
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.utils.dateparse import parse_date

from accounts.models import User
from .forms import (
    ComplaintFeeForm,
    ComplaintFeedbackForm,
    ComplaintForm,
    ComplaintCategoryForm,
    EvidenceReviewForm,
    ComplaintReplyForm,
    ComplaintUpdateForm,
    EscalationForm,
    HearingAttendanceForm,
    HearingMediationForm,
    RespondentContactForm,
    RespondentForm,
    RespondentResponseForm,
    SecondNoticeForm,
)
from .models import (
    ActivityLog,
    Complaint,
    ComplaintCategory,
    ComplaintFeedback,
    ComplaintReply,
    ComplaintResponse,
    ComplaintStatusHistory,
    Escalation,
    HearingMediation,
    Notification,
    Respondent,
    RespondentEvidence,
    UploadedEvidence,
)
from .services import choose_auto_assignee, create_notification, get_staff_assignment_options, log_activity


ACTIVE_ASSIGNMENT_STATUSES = [
    Complaint.Status.PENDING,
    Complaint.Status.UNDER_REVIEW,
    Complaint.Status.RESPONDENT_NOT_CONTACTED,
    Complaint.Status.RESPONDENT_CONTACTED,
    Complaint.Status.WAITING_RESPONDENT_RESPONSE,
    Complaint.Status.RESPONDENT_RESPONSE_RECORDED,
    Complaint.Status.NO_RESPONSE,
    Complaint.Status.FAILED_TO_ATTEND,
    Complaint.Status.SECOND_NOTICE_SENT,
    Complaint.Status.HEARING_SCHEDULED,
    Complaint.Status.IN_MEDIATION,
    Complaint.Status.IN_PROGRESS,
]

IN_PROGRESS_SUMMARY_STATUSES = [
    Complaint.Status.UNDER_REVIEW,
    Complaint.Status.RESPONDENT_NOT_CONTACTED,
    Complaint.Status.RESPONDENT_CONTACTED,
    Complaint.Status.WAITING_RESPONDENT_RESPONSE,
    Complaint.Status.RESPONDENT_RESPONSE_RECORDED,
    Complaint.Status.NO_RESPONSE,
    Complaint.Status.FAILED_TO_ATTEND,
    Complaint.Status.SECOND_NOTICE_SENT,
    Complaint.Status.HEARING_SCHEDULED,
    Complaint.Status.IN_MEDIATION,
    Complaint.Status.IN_PROGRESS,
]

COMPLAINTS_PER_PAGE = 10
NOTIFICATIONS_PER_PAGE = 12


def paginate_queryset(request, queryset, per_page):
    paginator = Paginator(queryset, per_page)
    page_obj = paginator.get_page(request.GET.get("page"))
    query_params = request.GET.copy()
    query_params.pop("page", None)
    page_range = paginator.get_elided_page_range(page_obj.number, on_each_side=1, on_ends=1)
    return page_obj, query_params.urlencode(), page_range


STATUS_NOTIFICATION_MESSAGES = {
    Complaint.Status.UNDER_REVIEW: "Your complaint is now under review by the barangay office.",
    Complaint.Status.RESPONDENT_CONTACTED: "The other party involved in your complaint has been contacted by the barangay office.",
    Complaint.Status.SECOND_NOTICE_SENT: "A second notice has been recorded for the other party involved in your complaint.",
    Complaint.Status.RESOLVED: "Your complaint has been marked as resolved.",
    Complaint.Status.UNRESOLVED: "Your complaint has been marked as unresolved.",
    Complaint.Status.ESCALATED: "Your complaint remains unresolved and has been escalated to a higher authority for further action.",
    Complaint.Status.CLOSED: "Your complaint has been closed.",
}


BARANGAY_DOCUMENT_HEADER = [
    "Republic of the Philippines",
    "Province of Negros Oriental",
    "Municipality of Santa Catalina",
    "BARANGAY CAWITAN",
]
BARANGAY_OFFICE_NAME = "Office of the Barangay Cawitan Complaint Management System"
BARANGAY_DOCUMENT_FOOTER = "This document is system-generated by Barangay Cawitan and is valid for official complaint monitoring and records use."


def staff_or_admin_required(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated and (request.user.is_staff_member or request.user.is_barangay_admin):
            return view_func(request, *args, **kwargs)
        messages.error(request, "Only barangay staff or admins can access that page.")
        return redirect("dashboard:home")

    return wrapper


def admin_required(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_barangay_admin:
            return view_func(request, *args, **kwargs)
        messages.error(request, "Only admins can access that page.")
        return redirect("dashboard:home")

    return wrapper


def record_status_change(complaint, old_status, new_status, user, public_remarks="", internal_remarks="", remarks=""):
    if old_status == new_status and not (public_remarks or internal_remarks or remarks):
        return
    ComplaintStatusHistory.objects.create(
        complaint=complaint,
        old_status=old_status if old_status != new_status else "",
        new_status=new_status,
        changed_by=user,
        remarks=remarks,
        public_remarks=public_remarks,
        internal_remarks=internal_remarks,
    )


def notify_complainant_for_status(complaint, status, fallback_message=None):
    message = STATUS_NOTIFICATION_MESSAGES.get(status) or fallback_message
    if not message:
        message = f"Your complaint '{complaint.title}' is now {complaint.get_status_display()}."
    create_notification(
        user=complaint.resident,
        complaint=complaint,
        message=message,
        notification_type=Notification.Type.STATUS_CHANGED,
    )


def generate_fee_receipt_number(complaint):
    year = timezone.localdate().year
    return f"FEE-{year}-CMP{complaint.pk:05d}"


def get_or_create_respondent(complaint):
    respondent, _ = Respondent.objects.get_or_create(
        complaint=complaint,
        defaults={"full_name": "Unknown"},
    )
    return respondent


def create_uploaded_evidence(complaint, file, user, evidence_type=UploadedEvidence.EvidenceType.INITIAL, description=""):
    evidence = UploadedEvidence.objects.create(
        complaint=complaint,
        file=file,
        uploaded_by=user,
        evidence_type=evidence_type,
        description=description,
        file_size=getattr(file, "size", 0) or 0,
        content_type=getattr(file, "content_type", "") or "",
    )
    log_activity(
        actor=user,
        complaint=complaint,
        action=ActivityLog.Action.EVIDENCE_UPLOADED,
        target=evidence,
        summary=f"Evidence uploaded for complaint '{complaint.title}'.",
    )
    return evidence


def build_complaint_timeline(complaint, *, staff_view=False):
    timeline = [
        {
            "when": complaint.created_at,
            "title": "Complaint submitted",
            "body": "The complaint record was created.",
            "kind": "submitted",
            "is_public": True,
        }
    ]
    for item in complaint.status_history.all():
        if not staff_view and not item.public_remarks:
            continue
        title = item.get_new_status_display()
        if staff_view and item.old_status:
            title = f"{item.get_old_status_display()} to {item.get_new_status_display()}"
        timeline.append(
            {
                "when": item.changed_at,
                "title": title,
                "body": item.public_remarks or item.remarks or item.internal_remarks,
                "actor": item.changed_by,
                "kind": "status",
                "is_public": bool(item.public_remarks),
            }
        )
    for hearing in complaint.hearings.all():
        timeline.append(
            {
                "when": timezone.make_aware(
                    datetime.combine(hearing.date, hearing.time),
                    timezone.get_current_timezone(),
                ),
                "title": "Hearing / mediation scheduled",
                "body": f"{hearing.purpose} at {hearing.location}. {hearing.remarks}".strip(),
                "actor": hearing.created_by,
                "kind": "hearing",
                "is_public": True,
            }
        )
    if staff_view:
        for reply in complaint.replies.all():
            timeline.append(
                {
                    "when": reply.created_at,
                    "title": "Follow-up reply",
                    "body": reply.message,
                    "actor": reply.author,
                    "kind": "reply",
                    "is_public": reply.is_public,
                }
            )
        for response in complaint.responses.all():
            timeline.append(
                {
                    "when": response.created_at,
                    "title": response.get_source_display(),
                    "body": response.remarks,
                    "actor": response.responder,
                    "kind": "response",
                    "is_public": response.is_public,
                }
            )
        for log in complaint.activity_logs.all():
            timeline.append(
                {
                    "when": log.created_at,
                    "title": log.get_action_display(),
                    "body": log.summary,
                    "actor": log.actor,
                    "kind": "activity",
                    "is_public": False,
                }
            )
    return sorted(timeline, key=lambda item: item["when"], reverse=True)


@login_required
def complaint_list_view(request):
    if request.user.is_barangay_admin:
        complaints = Complaint.objects.select_related("resident", "assigned_to", "category")
    elif request.user.is_staff_member:
        complaints = Complaint.objects.filter(
            Q(assigned_to=request.user) | Q(assigned_to__isnull=True)
        ).select_related("resident", "assigned_to", "category")
    else:
        complaints = Complaint.objects.filter(resident=request.user).select_related("resident", "assigned_to", "category")

    all_complaints = complaints
    status = request.GET.get("status")
    priority = request.GET.get("priority")
    search = request.GET.get("q", "").strip()
    if status:
        complaints = complaints.filter(status=status)
    if priority:
        complaints = complaints.filter(priority=priority)
    if search:
        search_filter = (
            Q(title__icontains=search)
            | Q(description__icontains=search)
            | Q(category__name__icontains=search)
            | Q(resident__first_name__icontains=search)
            | Q(resident__last_name__icontains=search)
            | Q(resident__username__icontains=search)
            | Q(assigned_to__first_name__icontains=search)
            | Q(assigned_to__last_name__icontains=search)
            | Q(assigned_to__username__icontains=search)
        )
        if search.isdigit():
            search_filter |= Q(id=int(search))
        complaints = complaints.filter(search_filter)
    status_counts = {
        item["status"]: item["total"]
        for item in all_complaints.values("status").annotate(total=Count("id"))
    }
    selected_status_label = dict(Complaint.Status.choices).get(status, "All statuses")
    selected_priority_label = dict(Complaint.Priority.choices).get(priority, "All priorities")
    filtered_count = complaints.count()
    page_obj, pagination_querystring, pagination_range = paginate_queryset(request, complaints, COMPLAINTS_PER_PAGE)

    return render(
        request,
        "complaints/complaint_list.html",
        {
            "complaints": page_obj.object_list,
            "page_obj": page_obj,
            "pagination_querystring": pagination_querystring,
            "pagination_range": pagination_range,
            "status_choices": Complaint.Status.choices,
            "priority_choices": Complaint.Priority.choices,
            "selected_status": status,
            "selected_status_label": selected_status_label,
            "selected_priority": priority,
            "selected_priority_label": selected_priority_label,
            "search_query": search,
            "total_count": all_complaints.count(),
            "pending_count": status_counts.get(Complaint.Status.PENDING, 0),
            "in_progress_count": sum(status_counts.get(status, 0) for status in IN_PROGRESS_SUMMARY_STATUSES),
            "resolved_count": status_counts.get(Complaint.Status.RESOLVED, 0),
            "filtered_count": filtered_count,
        },
    )


@login_required
def submit_complaint_view(request):
    if not request.user.is_resident:
        messages.error(request, "Only residents can submit complaints.")
        return redirect("dashboard:home")
    try:
        resident_profile = request.user.resident_profile
    except Exception:
        resident_profile = None
    if not resident_profile or resident_profile.verification_status != resident_profile.VerificationStatus.VERIFIED:
        messages.error(request, "Your resident account must be verified before you can submit a complaint.")
        return redirect("accounts:profile")

    initial = {}
    if resident_profile.phone_number:
        initial["contact_number"] = resident_profile.phone_number
    form = ComplaintForm(request.POST or None, request.FILES or None, initial=initial)
    if request.method == "POST" and form.is_valid():
        complaint = form.save(commit=False)
        complaint.resident = request.user
        complaint.consented_at = timezone.now()
        complaint.save()
        Respondent.objects.create(
            complaint=complaint,
            full_name=form.cleaned_data.get("respondent_full_name") or "Unknown",
            contact_number=form.cleaned_data.get("respondent_contact_number", ""),
            address=form.cleaned_data.get("respondent_address", ""),
            relationship_to_complainant=form.cleaned_data.get("respondent_relationship_to_complainant", ""),
            is_known_to_complainant=form.cleaned_data.get("respondent_is_known_to_complainant", True),
            identifying_details=form.cleaned_data.get("respondent_identifying_details", ""),
            remarks=form.cleaned_data.get("respondent_remarks", ""),
        )
        auto_assignee = choose_auto_assignee(complaint)
        if auto_assignee:
            complaint.assigned_to = auto_assignee
            complaint.save(update_fields=["assigned_to"])
        ComplaintStatusHistory.objects.create(
            complaint=complaint,
            new_status=complaint.status,
            changed_by=request.user,
            remarks="Complaint submitted.",
            public_remarks="Your complaint has been submitted successfully.",
        )
        for evidence_file in form.cleaned_data.get("evidence", []):
            create_uploaded_evidence(complaint, evidence_file, request.user)
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.COMPLAINT_SUBMITTED,
            target=complaint,
            summary=f"Complaint '{complaint.title}' submitted.",
        )
        create_notification(
            user=request.user,
            complaint=complaint,
            message=f"Your complaint '{complaint.title}' was submitted successfully.",
            notification_type=Notification.Type.SUBMITTED,
        )
        if auto_assignee:
            create_notification(
                user=auto_assignee,
                complaint=complaint,
                message=f"You were automatically assigned complaint '{complaint.title}'.",
                notification_type=Notification.Type.ASSIGNED,
            )
            create_notification(
                user=request.user,
                complaint=complaint,
                message=(
                    f"Your complaint '{complaint.title}' was assigned to "
                    f"{auto_assignee.get_full_name() or auto_assignee.username}."
                ),
                notification_type=Notification.Type.ASSIGNED,
            )
        messages.success(request, "Complaint submitted successfully.")
        return redirect(complaint.get_absolute_url())

    return render(request, "complaints/submit_complaint.html", {"form": form})


@login_required
def complaint_detail_view(request, pk):
    complaint = get_object_or_404(
        Complaint.objects.select_related("resident", "assigned_to", "category").prefetch_related(
            "status_history",
            "hearings",
            "evidence_files",
            "respondent_evidence_files",
            "responses",
            "replies",
            "activity_logs",
        ),
        pk=pk,
    )
    can_view = (
        request.user.is_barangay_admin
        or complaint.resident == request.user
        or (
            request.user.is_staff_member
            and (complaint.assigned_to == request.user or complaint.assigned_to is None)
        )
    )
    if not can_view:
        messages.error(request, "You do not have permission to view this complaint.")
        return redirect("complaints:list")

    action = request.POST.get("workflow_action") if request.method == "POST" else None
    existing_feedback = getattr(complaint, "feedback", None)
    can_submit_feedback = (
        request.user == complaint.resident
        and complaint.status == Complaint.Status.RESOLVED
        and existing_feedback is None
    )
    reply_form = ComplaintReplyForm(
        request.POST if action == "reply" else None,
        request.FILES if action == "reply" else None,
    )
    feedback_form = ComplaintFeedbackForm(request.POST if action == "feedback" else None)
    if request.method == "POST" and action == "reply":
        if complaint.is_closed:
            messages.error(request, "This complaint is closed and cannot receive new replies.")
            return redirect(complaint.get_absolute_url())
        if reply_form.is_valid():
            reply = reply_form.save(commit=False)
            reply.complaint = complaint
            reply.author = request.user
            if request.user.is_staff_member or request.user.is_barangay_admin:
                reply.is_public = True
            if reply.attachment:
                reply.attachment_size = reply.attachment.size
                reply.attachment_content_type = getattr(reply.attachment, "content_type", "") or ""
            reply.save()
            if request.user == complaint.resident:
                recipient_ids = list(
                    User.objects.filter(Q(role=User.Role.ADMIN) | Q(is_superuser=True))
                    .values_list("id", flat=True)
                    .distinct()
                )
                if complaint.assigned_to:
                    recipient_ids.append(complaint.assigned_to_id)
                for recipient in User.objects.filter(id__in=set(recipient_ids)):
                    create_notification(
                        user=recipient,
                        complaint=complaint,
                        message=f"Resident added a follow-up to complaint '{complaint.title}'.",
                        notification_type=Notification.Type.REMARKS_ADDED,
                    )
            else:
                create_notification(
                    user=complaint.resident,
                    complaint=complaint,
                    message=f"Barangay staff replied to your complaint '{complaint.title}'.",
                    notification_type=Notification.Type.REMARKS_ADDED,
                )
            messages.success(request, "Reply added successfully.")
            return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "feedback":
        if request.user != complaint.resident:
            messages.error(request, "Only the complainant can submit feedback.")
            return redirect(complaint.get_absolute_url())
        if complaint.status != Complaint.Status.RESOLVED:
            messages.error(request, "Feedback can only be submitted after the complaint is resolved.")
            return redirect(complaint.get_absolute_url())
        if existing_feedback is not None:
            messages.error(request, "Feedback has already been submitted for this complaint.")
            return redirect(complaint.get_absolute_url())
        if feedback_form.is_valid():
            feedback = feedback_form.save(commit=False)
            feedback.complaint = complaint
            feedback.resident = request.user
            feedback.save()
            log_activity(
                actor=request.user,
                complaint=complaint,
                action=ActivityLog.Action.FEEDBACK_SUBMITTED,
                target=feedback,
                summary=f"Resident feedback submitted for complaint '{complaint.title}'.",
                metadata={"rating": feedback.rating, "resolution_accepted": feedback.resolution_accepted},
            )
            messages.success(request, "Thank you. Your feedback has been recorded.")
            return redirect(complaint.get_absolute_url())

    if request.method == "POST" and request.POST.get("workflow_action") == "evidence_review":
        if not (request.user.is_staff_member or request.user.is_barangay_admin):
            messages.error(request, "Only staff or admins can review evidence.")
            return redirect(complaint.get_absolute_url())
        evidence_kind = request.POST.get("evidence_kind")
        evidence_id = request.POST.get("evidence_id")
        evidence_model = RespondentEvidence if evidence_kind == "respondent" else UploadedEvidence
        evidence = get_object_or_404(evidence_model, pk=evidence_id, complaint=complaint)
        review_form = EvidenceReviewForm(request.POST)
        if review_form.is_valid():
            evidence.review_status = review_form.cleaned_data["review_status"]
            evidence.review_remarks = review_form.cleaned_data["review_remarks"]
            evidence.reviewed_by = request.user
            evidence.reviewed_at = timezone.now()
            evidence.save(update_fields=["review_status", "review_remarks", "reviewed_by", "reviewed_at"])
            log_activity(
                actor=request.user,
                complaint=complaint,
                action=ActivityLog.Action.EVIDENCE_REVIEWED,
                target=evidence,
                summary=f"Evidence marked {evidence.get_review_status_display()} for complaint '{complaint.title}'.",
            )
            messages.success(request, "Evidence review saved.")
            return redirect(complaint.get_absolute_url())

    latest_hearing = complaint.hearings.first()
    public_status_history = complaint.status_history.exclude(public_remarks="")
    public_responses = complaint.responses.filter(is_public=True)
    staff_view = request.user.is_staff_member or request.user.is_barangay_admin
    return render(
        request,
        "complaints/complaint_detail.html",
        {
            "complaint": complaint,
            "latest_hearing": latest_hearing,
            "public_status_history": public_status_history,
            "public_responses": public_responses,
            "reply_form": reply_form,
            "feedback_form": feedback_form,
            "existing_feedback": existing_feedback,
            "can_submit_feedback": can_submit_feedback,
            "complaint_timeline": build_complaint_timeline(complaint, staff_view=staff_view),
            "evidence_review_choices": UploadedEvidence.ReviewStatus.choices,
        },
    )


@login_required
def notifications_view(request):
    notifications = Notification.objects.filter(user=request.user).select_related("complaint")
    unread_count = notifications.filter(is_read=False).count()
    page_obj, pagination_querystring, pagination_range = paginate_queryset(request, notifications, NOTIFICATIONS_PER_PAGE)
    return render(
        request,
        "complaints/notifications.html",
        {
            "notifications": page_obj.object_list,
            "page_obj": page_obj,
            "pagination_querystring": pagination_querystring,
            "pagination_range": pagination_range,
            "unread_count": unread_count,
        },
    )


@login_required
def mark_all_notifications_read_view(request):
    if request.method == "POST":
        Notification.objects.filter(user=request.user, is_read=False).update(is_read=True, read_at=timezone.now())
        messages.success(request, "All notifications marked as read.")
    return redirect("complaints:notifications")


@login_required
def notification_view_redirect(request, pk):
    notification = get_object_or_404(Notification, pk=pk, user=request.user)
    if not notification.is_read:
        notification.is_read = True
        notification.read_at = timezone.now()
        notification.save(update_fields=["is_read", "read_at"])

    if notification.link_target:
        return redirect(notification.link_target)
    if notification.complaint:
        return redirect(notification.complaint.get_absolute_url())
    return redirect("complaints:notifications")


def draw_official_pdf_header(pdf, *, width, height, title, subtitle="", generated_by=None):
    from reportlab.lib import colors

    margin = 50
    header_center_x = width / 2
    seal_center_x = margin + 34
    seal_center_y = height - 62

    pdf.setStrokeColor(colors.HexColor("#1E3A8A"))
    pdf.setLineWidth(1.4)
    pdf.circle(seal_center_x, seal_center_y, 28, stroke=1, fill=0)
    pdf.setStrokeColor(colors.HexColor("#94A3B8"))
    pdf.setLineWidth(0.6)
    pdf.circle(seal_center_x, seal_center_y, 22, stroke=1, fill=0)
    pdf.setFont("Helvetica-Bold", 8)
    pdf.drawCentredString(seal_center_x, seal_center_y + 2, "BC")
    pdf.setFont("Helvetica", 7)
    pdf.drawCentredString(seal_center_x, seal_center_y - 8, "SEAL")

    y = height - 35
    pdf.setFont("Helvetica", 9)
    for line in BARANGAY_DOCUMENT_HEADER[:3]:
        pdf.drawCentredString(header_center_x, y, line)
        y -= 11
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawCentredString(header_center_x, y, BARANGAY_DOCUMENT_HEADER[3])
    y -= 13
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawCentredString(header_center_x, y, BARANGAY_OFFICE_NAME)
    y -= 15
    pdf.setStrokeColor(colors.HexColor("#1E3A8A"))
    pdf.setLineWidth(1.2)
    pdf.line(margin, y, width - margin, y)
    y -= 3
    pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
    pdf.setLineWidth(0.5)
    pdf.line(margin, y, width - margin, y)
    y -= 24
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawCentredString(header_center_x, y, title.upper())
    if subtitle:
        y -= 14
        pdf.setFont("Helvetica", 9)
        pdf.drawCentredString(header_center_x, y, subtitle)
    y -= 20
    pdf.setFont("Helvetica", 8)
    generated_at = timezone.localtime(timezone.now()).strftime("%B %d, %Y %I:%M %p")
    pdf.drawString(50, y, f"Generated: {generated_at}")
    if generated_by:
        pdf.drawRightString(width - 50, y, f"Generated by: {generated_by}")
    return y - 24


def draw_official_pdf_footer(pdf, *, width, page_number):
    from reportlab.lib import colors

    pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
    pdf.setLineWidth(0.7)
    pdf.line(50, 42, width - 50, 42)
    pdf.setFont("Helvetica", 7)
    pdf.setFillColor(colors.HexColor("#475569"))
    pdf.drawString(50, 30, BARANGAY_DOCUMENT_FOOTER)
    pdf.drawRightString(width - 50, 30, f"Page {page_number}")
    pdf.setFillColor(colors.black)


def draw_wrapped_pdf_text(pdf, text, x, y, *, max_chars=92, line_height=14, font="Helvetica", size=9):
    pdf.setFont(font, size)
    paragraphs = str(text).splitlines() or [""]
    for paragraph in paragraphs:
        words = paragraph.split()
        if not words:
            y -= line_height
            continue
        line = ""
        for word in words:
            candidate = f"{line} {word}".strip()
            if len(candidate) > max_chars:
                pdf.drawString(x, y, line)
                y -= line_height
                line = word
            else:
                line = candidate
        if line:
            pdf.drawString(x, y, line)
            y -= line_height
    return y


def build_notice_pdf_response(request, complaint, title, lines, filename):
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except ImportError:
        messages.error(request, "PDF generation needs reportlab. Install requirements.txt, then try again.")
        return None

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    page_number = 1
    generated_by = request.user.get_full_name() or request.user.username
    y = draw_official_pdf_header(
        pdf,
        width=width,
        height=height,
        title=title,
        subtitle=f"Complaint Case No. CMP-{complaint.id:05d}",
        generated_by=generated_by,
    )
    pdf.setFont("Helvetica", 9)
    for line in lines:
        if y < 60:
            draw_official_pdf_footer(pdf, width=width, page_number=page_number)
            pdf.showPage()
            page_number += 1
            y = draw_official_pdf_header(
                pdf,
                width=width,
                height=height,
                title=title,
                subtitle=f"Complaint Case No. CMP-{complaint.id:05d}",
                generated_by=generated_by,
            )
        if line == "":
            y -= 10
            continue
        if ":" in str(line):
            label, value = str(line).split(":", 1)
            pdf.setFont("Helvetica-Bold", 9)
            pdf.drawString(50, y, f"{label}:")
            y = draw_wrapped_pdf_text(pdf, value.strip(), 165, y, max_chars=72, line_height=14)
        else:
            y = draw_wrapped_pdf_text(pdf, line, 50, y, max_chars=92, line_height=14)
        y -= 3
    y -= 18
    pdf.setFont("Helvetica", 9)
    pdf.drawString(50, max(y, 92), "Prepared by:")
    pdf.line(50, max(y, 92) - 28, 210, max(y, 92) - 28)
    pdf.drawString(50, max(y, 92) - 40, generated_by)
    pdf.drawRightString(width - 50, max(y, 92), "Received by:")
    pdf.line(width - 210, max(y, 92) - 28, width - 50, max(y, 92) - 28)
    pdf.drawRightString(width - 50, max(y, 92) - 40, "Signature over printed name")
    draw_official_pdf_footer(pdf, width=width, page_number=page_number)
    pdf.save()
    buffer.seek(0)
    response = HttpResponse(buffer.getvalue(), content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return response


@login_required
@staff_or_admin_required
def complaint_notice_pdf_view(request, pk, notice_type):
    complaint = get_object_or_404(
        Complaint.objects.select_related("resident", "assigned_to", "category").prefetch_related("hearings"),
        pk=pk,
    )
    if request.user.is_staff_member and complaint.assigned_to not in (request.user, None):
        messages.error(request, "You can only generate notices for complaints assigned to you.")
        return redirect("complaints:list")

    latest_hearing = complaint.hearings.first()
    respondent = getattr(complaint, "respondent", None)
    base_lines = [
        f"Complaint No.: CMP-{complaint.id:05d}",
        f"Title: {complaint.title}",
        f"Complainant: {complaint.resident.get_full_name() or complaint.resident.username}",
        f"Respondent: {respondent.full_name if respondent else 'Unknown'}",
        f"Category: {complaint.category.name if complaint.category else 'Uncategorized'}",
        f"Status: {complaint.get_status_display()}",
        f"Incident Location: {complaint.incident_location}",
        f"Incident Date: {complaint.incident_date or 'Not recorded'}",
        "",
    ]
    if notice_type == "hearing":
        if not latest_hearing:
            messages.error(request, "Schedule a hearing before generating a hearing notice.")
            return redirect(complaint.get_absolute_url())
        title = "Hearing / Mediation Notice"
        lines = base_lines + [
            "Official Notice: You are hereby notified to appear before the Barangay Cawitan office for the scheduled hearing or mediation below.",
            f"Date: {latest_hearing.date:%B %d, %Y}",
            f"Time: {latest_hearing.time:%I:%M %p}",
            f"Location: {latest_hearing.location}",
            f"Purpose: {latest_hearing.purpose}",
            f"Instructions: {latest_hearing.remarks or 'Please attend on time.'}",
            "Reminder: Bring any supporting documents, evidence, and valid identification. Failure to attend may be recorded in the complaint case file.",
        ]
    elif notice_type == "second-notice":
        title = "Second Notice"
        lines = base_lines + [
            "Official Notice: This second notice is issued because the respondent did not respond, failed to attend, or requires another formal notice from the Barangay Cawitan office.",
            f"Notice Date: {complaint.second_notice_date or timezone.localdate()}",
            f"Method: {complaint.second_notice_method or 'Not recorded'}",
            f"Remarks: {complaint.second_notice_remarks or 'Second notice recorded by the barangay office.'}",
            "Reminder: Please coordinate with the barangay office immediately to avoid further action or escalation.",
        ]
    else:
        title = "Complaint Resolution Summary"
        lines = base_lines + [
            f"Resolved At: {complaint.resolved_at:%B %d, %Y %I:%M %p}" if complaint.resolved_at else "Resolved At: Not recorded",
            f"Public Remarks: {complaint.public_remarks or 'No public remarks recorded.'}",
            f"Escalation: {complaint.escalation.escalated_to if hasattr(complaint, 'escalation') else 'Not escalated'}",
            f"Assigned Staff: {complaint.assigned_to.get_full_name() or complaint.assigned_to.username if complaint.assigned_to else 'Unassigned'}",
            f"Filing Fee: {complaint.get_fee_status_display()}",
            "Certification: This summary reflects the complaint status and records encoded in the Barangay Cawitan Complaint Management System as of the generation date.",
        ]
    log_activity(
        actor=request.user,
        complaint=complaint,
        action=ActivityLog.Action.NOTICE_GENERATED,
        target=complaint,
        summary=f"{title} generated for complaint '{complaint.title}'.",
        metadata={"notice_type": notice_type},
    )
    response = build_notice_pdf_response(request, complaint, title, lines, f"complaint-{complaint.pk}-{notice_type}.pdf")
    return response or redirect(complaint.get_absolute_url())


def get_workflow_guidance(complaint, action=None):
    action_tabs = {
        "complaint": "assignment",
        "respondent": "respondent",
        "contact": "contact",
        "response": "contact",
        "hearing": "hearing",
        "attendance": "hearing",
        "second_notice": "resolution",
        "escalation": "resolution",
        "fee": "fee",
    }
    status_guidance = {
        Complaint.Status.PENDING: (
            "assignment",
            "Assign and triage this complaint",
            "Set the priority, choose a handler, and add any initial public or internal remarks.",
            "bi-person-check-fill",
        ),
        Complaint.Status.UNDER_REVIEW: (
            "respondent",
            "Complete respondent details",
            "Review the other party information before contact or mediation work starts.",
            "bi-person-lines-fill",
        ),
        Complaint.Status.RESPONDENT_NOT_CONTACTED: (
            "contact",
            "Record the first contact attempt",
            "Capture how the respondent was contacted and whether they already gave a response.",
            "bi-telephone-fill",
        ),
        Complaint.Status.RESPONDENT_CONTACTED: (
            "contact",
            "Record the respondent response",
            "Add the response statement or supporting attachment once the other party replies.",
            "bi-chat-left-text-fill",
        ),
        Complaint.Status.WAITING_RESPONDENT_RESPONSE: (
            "contact",
            "Follow up on the respondent response",
            "Update the response status, or record no response if the deadline has passed.",
            "bi-hourglass-split",
        ),
        Complaint.Status.RESPONDENT_RESPONSE_RECORDED: (
            "hearing",
            "Schedule hearing or mediation",
            "Move the complaint into a scheduled hearing or mediation session if needed.",
            "bi-calendar-event-fill",
        ),
        Complaint.Status.NO_RESPONSE: (
            "resolution",
            "Record a second notice",
            "Use the second notice section when the respondent did not answer the first contact.",
            "bi-envelope-paper-fill",
        ),
        Complaint.Status.FAILED_TO_ATTEND: (
            "resolution",
            "Record second notice or escalate",
            "Use the resolution tools when attendance failed or further action is required.",
            "bi-exclamation-triangle-fill",
        ),
        Complaint.Status.SECOND_NOTICE_SENT: (
            "hearing",
            "Schedule the next hearing step",
            "After the second notice, schedule or update hearing and mediation details.",
            "bi-calendar-plus-fill",
        ),
        Complaint.Status.HEARING_SCHEDULED: (
            "hearing",
            "Record attendance and result",
            "After the scheduled date, record attendance and the mediation outcome.",
            "bi-clipboard2-check-fill",
        ),
        Complaint.Status.IN_MEDIATION: (
            "hearing",
            "Update mediation result",
            "Record whether the mediation resolved the issue, needs rescheduling, or must be escalated.",
            "bi-people-fill",
        ),
        Complaint.Status.IN_PROGRESS: (
            "resolution",
            "Add resolution updates",
            "Use status remarks, escalation, or final resolution updates as the case progresses.",
            "bi-arrow-repeat",
        ),
        Complaint.Status.UNRESOLVED: (
            "resolution",
            "Escalate or close the unresolved case",
            "Escalate when barangay-level handling cannot resolve the complaint.",
            "bi-arrow-up-right-circle-fill",
        ),
        Complaint.Status.ESCALATED: (
            "resolution",
            "Track escalation outcome",
            "Keep internal notes and update the status when a higher authority responds.",
            "bi-arrow-up-right-circle-fill",
        ),
        Complaint.Status.RESOLVED: (
            "resolution",
            "Review the resolved complaint",
            "The complaint is resolved. Add only necessary final notes or corrections.",
            "bi-check-circle-fill",
        ),
        Complaint.Status.CLOSED: (
            "resolution",
            "Complaint is closed",
            "This complaint is closed. Review details before making any further change.",
            "bi-lock-fill",
        ),
        Complaint.Status.REJECTED: (
            "resolution",
            "Review rejected complaint",
            "Check remarks and supporting details before reopening or changing the outcome.",
            "bi-x-circle-fill",
        ),
    }
    active_tab, title, body, icon = status_guidance.get(
        complaint.status,
        (
            "assignment",
            "Review complaint workflow",
            "Choose the section that matches the work you need to record.",
            "bi-kanban-fill",
        ),
    )
    return {
        "workflow_active_tab": action_tabs.get(action, active_tab),
        "workflow_recommendation_title": title,
        "workflow_recommendation_body": body,
        "workflow_recommendation_icon": icon,
    }


@login_required
@staff_or_admin_required
def update_complaint_view(request, pk):
    complaint = get_object_or_404(Complaint.objects.select_related("resident", "assigned_to", "category"), pk=pk)
    if request.user.is_staff_member and complaint.assigned_to not in (request.user, None):
        messages.error(request, "You can only update complaints assigned to you.")
        return redirect("complaints:list")

    respondent = get_or_create_respondent(complaint)
    latest_hearing = complaint.hearings.first()
    escalation = getattr(complaint, "escalation", None)
    action = request.POST.get("workflow_action") if request.method == "POST" else None
    form = ComplaintUpdateForm(
        request.POST if action == "complaint" else None,
        instance=complaint,
        complaint=complaint,
        prefix="complaint",
    )
    respondent_form = RespondentForm(
        request.POST if action == "respondent" else None,
        instance=respondent,
        prefix="respondent",
    )
    contact_form = RespondentContactForm(
        request.POST if action == "contact" else None,
        instance=respondent,
        prefix="contact",
    )
    response_form = RespondentResponseForm(
        request.POST if action == "response" else None,
        request.FILES if action == "response" else None,
        prefix="response",
    )
    hearing_form = HearingMediationForm(request.POST if action == "hearing" else None, prefix="hearing")
    fee_form = ComplaintFeeForm(
        request.POST if action == "fee" else None,
        instance=complaint,
        prefix="fee",
        can_finalize_fee=request.user.is_barangay_admin,
    )
    attendance_form = (
        HearingAttendanceForm(
            request.POST if action == "attendance" else None,
            instance=latest_hearing,
            prefix="attendance",
        )
        if latest_hearing
        else None
    )
    second_notice_form = SecondNoticeForm(
        request.POST if action == "second_notice" else None,
        instance=complaint,
        prefix="second_notice",
    )
    escalation_form = EscalationForm(
        request.POST if action == "escalation" else None,
        instance=escalation,
        prefix="escalation",
    )
    if request.user.is_staff_member:
        form.fields.pop("assigned_to")
    workflow_context = get_workflow_guidance(complaint, action)

    if request.method == "POST" and action == "complaint":
        old_status = complaint.status
        old_priority = complaint.priority
        old_assigned_to = complaint.assigned_to
        if not form.is_valid():
            return render(
                request,
                "complaints/update_complaint.html",
                {
                    "form": form,
                    "complaint": complaint,
                    "respondent": respondent,
                    "respondent_form": respondent_form,
                    "contact_form": contact_form,
                    "response_form": response_form,
                    "hearing_form": hearing_form,
                    "attendance_form": attendance_form,
                    "second_notice_form": second_notice_form,
                    "escalation_form": escalation_form,
                    "fee_form": fee_form,
                    "latest_hearing": latest_hearing,
                    "staff_assignment_options": get_staff_assignment_options(complaint) if request.user.is_barangay_admin else [],
                    **workflow_context,
                },
            )
        complaint = form.save(commit=False)
        if request.user.is_staff_member and complaint.assigned_to is None:
            complaint.assigned_to = request.user
        if old_priority != complaint.priority and not complaint.is_closed:
            complaint.set_deadline(reference_time=timezone.now())
        if complaint.status == Complaint.Status.RESOLVED and old_status != Complaint.Status.RESOLVED:
            complaint.resolved_at = timezone.now()
        elif old_status == Complaint.Status.RESOLVED and complaint.status != Complaint.Status.RESOLVED:
            complaint.resolved_at = None
        complaint.save()
        public_remarks = form.cleaned_data.get("public_remarks_input", "").strip()
        internal_remarks = form.cleaned_data.get("internal_remarks_input", "").strip()
        if public_remarks:
            complaint.public_remarks = public_remarks
        if internal_remarks:
            complaint.internal_remarks = internal_remarks
        if public_remarks or internal_remarks:
            complaint.save(update_fields=["public_remarks", "internal_remarks", "updated_at"])
        if public_remarks:
            ComplaintResponse.objects.create(
                complaint=complaint,
                responder=request.user,
                remarks=public_remarks,
                is_public=True,
                status_after_response=complaint.status,
            )
        if internal_remarks:
            ComplaintResponse.objects.create(
                complaint=complaint,
                responder=request.user,
                remarks=internal_remarks,
                is_public=False,
                status_after_response=complaint.status,
            )
        if old_status != complaint.status:
            record_status_change(
                complaint,
                old_status,
                complaint.status,
                request.user,
                public_remarks=public_remarks or complaint.public_remarks,
                internal_remarks=internal_remarks,
            )
            notify_complainant_for_status(complaint, complaint.status)
        elif public_remarks or internal_remarks:
            record_status_change(
                complaint,
                complaint.status,
                complaint.status,
                request.user,
                public_remarks=public_remarks,
                internal_remarks=internal_remarks,
            )
        if public_remarks:
            create_notification(
                user=complaint.resident,
                complaint=complaint,
                message=f"New remarks were added to your complaint '{complaint.title}'.",
                notification_type=Notification.Type.REMARKS_ADDED,
            )
        if complaint.assigned_to and complaint.assigned_to != old_assigned_to:
            log_activity(
                actor=request.user,
                complaint=complaint,
                action=ActivityLog.Action.ASSIGNMENT_CHANGED,
                target=complaint.assigned_to,
                summary=f"Complaint '{complaint.title}' assigned to {complaint.assigned_to.get_full_name() or complaint.assigned_to.username}.",
                metadata={"old_assigned_to": old_assigned_to_id if (old_assigned_to_id := getattr(old_assigned_to, "id", None)) else None},
            )
            create_notification(
                user=complaint.assigned_to,
                complaint=complaint,
                message=f"You were assigned complaint '{complaint.title}'.",
                notification_type=Notification.Type.ASSIGNED,
            )
            create_notification(
                user=complaint.resident,
                complaint=complaint,
                message=(
                    f"Your complaint '{complaint.title}' was assigned to "
                    f"{complaint.assigned_to.get_full_name() or complaint.assigned_to.username}."
                ),
                notification_type=Notification.Type.ASSIGNED,
            )
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.COMPLAINT_UPDATED,
            target=complaint,
            summary=f"Complaint '{complaint.title}' workflow updated.",
            metadata={"old_status": old_status, "new_status": complaint.status, "old_priority": old_priority, "new_priority": complaint.priority},
        )
        messages.success(request, "Complaint updated successfully.")
        return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "fee":
        old_fee_status = complaint.fee_status
        if request.user.is_staff_member and complaint.fee_status in (Complaint.FeeStatus.PAID, Complaint.FeeStatus.WAIVED):
            messages.error(request, "Only admins can change a finalized filing fee record.")
            return redirect(complaint.get_absolute_url())
        if fee_form.is_valid():
            complaint = fee_form.save(commit=False)
            if complaint.fee_status == Complaint.FeeStatus.PAID:
                complaint.fee_collected_by = request.user
                if not complaint.fee_receipt_number:
                    complaint.fee_receipt_number = generate_fee_receipt_number(complaint)
            elif complaint.fee_status in (Complaint.FeeStatus.NOT_REQUIRED, Complaint.FeeStatus.PENDING):
                complaint.fee_receipt_number = ""
                complaint.fee_paid_at = None
                complaint.fee_collected_by = None
                if complaint.fee_status in (Complaint.FeeStatus.NOT_REQUIRED, Complaint.FeeStatus.PENDING):
                    complaint.fee_amount = None
            elif complaint.fee_status == Complaint.FeeStatus.WAIVED:
                complaint.fee_receipt_number = ""
                complaint.fee_paid_at = None
                complaint.fee_collected_by = None
            complaint.save(
                update_fields=[
                    "fee_status",
                    "fee_amount",
                    "fee_receipt_number",
                    "fee_paid_at",
                    "fee_collected_by",
                    "fee_notes",
                    "updated_at",
                ]
            )
            fee_messages = {
                Complaint.FeeStatus.PENDING: (
                    f"Your complaint '{complaint.title}' has a pending filing fee. "
                    "Please visit the barangay office for official payment and receipt."
                ),
                Complaint.FeeStatus.PAID: (
                    f"Your filing fee for complaint '{complaint.title}' has been recorded"
                    f"{' with OR No. ' + complaint.fee_receipt_number if complaint.fee_receipt_number else ''}."
                ),
                Complaint.FeeStatus.WAIVED: f"Your filing fee for complaint '{complaint.title}' has been waived.",
            }
            if complaint.fee_status != old_fee_status and complaint.fee_status in fee_messages:
                create_notification(
                    user=complaint.resident,
                    complaint=complaint,
                    message=fee_messages[complaint.fee_status],
                    notification_type=Notification.Type.STATUS_CHANGED,
                )
            log_activity(
                actor=request.user,
                complaint=complaint,
                action=ActivityLog.Action.FEE_UPDATED,
                target=complaint,
                summary=f"Filing fee changed from {old_fee_status} to {complaint.fee_status}.",
                metadata={"old_fee_status": old_fee_status, "new_fee_status": complaint.fee_status},
            )
            messages.success(request, "Filing fee record updated.")
            return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "respondent" and respondent_form.is_valid():
        respondent_form.save()
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.COMPLAINT_UPDATED,
            target=respondent,
            summary=f"Respondent details updated for complaint '{complaint.title}'.",
        )
        messages.success(request, "Respondent details updated.")
        return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "contact" and contact_form.is_valid():
        old_status = complaint.status
        respondent = contact_form.save(commit=False)
        if respondent.contacted:
            respondent.contacted_by = request.user
            if not respondent.contact_date:
                respondent.contact_date = timezone.localdate()
            complaint.status = Complaint.Status.RESPONDENT_CONTACTED
        elif complaint.status == Complaint.Status.PENDING:
            complaint.status = Complaint.Status.RESPONDENT_NOT_CONTACTED
        if respondent.response_status == Respondent.ResponseStatus.RESPONDED:
            complaint.status = Complaint.Status.RESPONDENT_RESPONSE_RECORDED
        elif respondent.response_status == Respondent.ResponseStatus.NO_RESPONSE:
            complaint.status = Complaint.Status.NO_RESPONSE
        elif respondent.response_status == Respondent.ResponseStatus.FAILED_TO_ATTEND:
            complaint.status = Complaint.Status.FAILED_TO_ATTEND
        respondent.save()
        complaint.save(update_fields=["status", "updated_at"])
        public_remarks = ""
        if complaint.status == Complaint.Status.RESPONDENT_CONTACTED:
            public_remarks = "The other party involved in your complaint has been contacted by the barangay office."
        record_status_change(
            complaint,
            old_status,
            complaint.status,
            request.user,
            public_remarks=public_remarks,
            internal_remarks=respondent.contact_remarks,
        )
        notify_complainant_for_status(complaint, complaint.status)
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.COMPLAINT_UPDATED,
            target=respondent,
            summary=f"Respondent contact recorded for complaint '{complaint.title}'.",
        )
        messages.success(request, "Respondent contact details recorded.")
        return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "response" and response_form.is_valid():
        old_status = complaint.status
        response = response_form.save(commit=False)
        response.complaint = complaint
        response.responder = request.user
        response.source = ComplaintResponse.Source.RESPONDENT
        response.is_public = False
        response.status_after_response = Complaint.Status.RESPONDENT_RESPONSE_RECORDED
        response.save()
        respondent.response_status = Respondent.ResponseStatus.RESPONDED
        respondent.response_statement = response.remarks
        respondent.save(update_fields=["response_status", "response_statement", "updated_at"])
        if response_form.cleaned_data.get("evidence"):
            evidence = RespondentEvidence.objects.create(
                complaint=complaint,
                file=response_form.cleaned_data["evidence"],
                uploaded_by=request.user,
                evidence_type=RespondentEvidence.EvidenceType.RESPONSE,
                remarks=response_form.cleaned_data.get("evidence_remarks", ""),
                file_size=getattr(response_form.cleaned_data["evidence"], "size", 0) or 0,
                content_type=getattr(response_form.cleaned_data["evidence"], "content_type", "") or "",
            )
            log_activity(
                actor=request.user,
                complaint=complaint,
                action=ActivityLog.Action.EVIDENCE_UPLOADED,
                target=evidence,
                summary=f"Respondent evidence uploaded for complaint '{complaint.title}'.",
            )
        complaint.status = Complaint.Status.RESPONDENT_RESPONSE_RECORDED
        complaint.save(update_fields=["status", "updated_at"])
        record_status_change(
            complaint,
            old_status,
            complaint.status,
            request.user,
            public_remarks="The barangay office has recorded the other party's response.",
            internal_remarks=response.remarks,
        )
        notify_complainant_for_status(complaint, complaint.status)
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.COMPLAINT_UPDATED,
            target=response,
            summary=f"Respondent response recorded for complaint '{complaint.title}'.",
        )
        messages.success(request, "Respondent response recorded.")
        return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "hearing" and hearing_form.is_valid():
        old_status = complaint.status
        hearing = hearing_form.save(commit=False)
        hearing.complaint = complaint
        hearing.created_by = request.user
        hearing.save()
        complaint.status = Complaint.Status.HEARING_SCHEDULED
        complaint.save(update_fields=["status", "updated_at"])
        public_remarks = (
            f"Your complaint hearing has been scheduled on {hearing.date} "
            f"at {hearing.time.strftime('%I:%M %p')} in {hearing.location}. Please attend on time."
        )
        record_status_change(complaint, old_status, complaint.status, request.user, public_remarks=public_remarks)
        create_notification(
            user=complaint.resident,
            complaint=complaint,
            message=public_remarks,
            notification_type=Notification.Type.STATUS_CHANGED,
        )
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.HEARING_SCHEDULED,
            target=hearing,
            summary=f"Hearing scheduled for complaint '{complaint.title}' on {hearing.date}.",
        )
        messages.success(request, "Hearing or mediation schedule saved.")
        return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "attendance" and attendance_form and attendance_form.is_valid():
        old_status = complaint.status
        hearing = attendance_form.save(commit=False)
        hearing.attendance_recorded = True
        hearing.save()
        if hearing.mediation_result == HearingMediation.MediationResult.RESOLVED:
            complaint.status = Complaint.Status.RESOLVED
            complaint.resolved_at = timezone.now()
        elif hearing.mediation_result == HearingMediation.MediationResult.UNRESOLVED:
            complaint.status = Complaint.Status.UNRESOLVED
        elif hearing.mediation_result == HearingMediation.MediationResult.FOR_ESCALATION:
            complaint.status = Complaint.Status.UNRESOLVED
        elif hearing.mediation_result == HearingMediation.MediationResult.RESCHEDULED:
            complaint.status = Complaint.Status.HEARING_SCHEDULED
        else:
            complaint.status = Complaint.Status.IN_MEDIATION
        complaint.save(update_fields=["status", "resolved_at", "updated_at"])
        public_remarks = hearing.agreement_remarks if hearing.mediation_result == HearingMediation.MediationResult.RESOLVED else ""
        record_status_change(
            complaint,
            old_status,
            complaint.status,
            request.user,
            public_remarks=public_remarks,
            internal_remarks=hearing.attendance_remarks,
        )
        notify_complainant_for_status(complaint, complaint.status)
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.COMPLAINT_UPDATED,
            target=hearing,
            summary=f"Hearing attendance/result recorded for complaint '{complaint.title}'.",
        )
        messages.success(request, "Attendance and mediation result recorded.")
        return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "second_notice" and second_notice_form.is_valid():
        old_status = complaint.status
        complaint = second_notice_form.save(commit=False)
        complaint.second_notice_sent = True
        if not complaint.second_notice_date:
            complaint.second_notice_date = timezone.localdate()
        complaint.status = Complaint.Status.SECOND_NOTICE_SENT
        complaint.save()
        record_status_change(
            complaint,
            old_status,
            complaint.status,
            request.user,
            public_remarks="A second notice has been recorded for the other party involved in your complaint.",
            internal_remarks=complaint.second_notice_remarks,
        )
        notify_complainant_for_status(complaint, complaint.status)
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.SECOND_NOTICE_RECORDED,
            target=complaint,
            summary=f"Second notice recorded for complaint '{complaint.title}'.",
        )
        messages.success(request, "Second notice recorded.")
        return redirect(complaint.get_absolute_url())

    if request.method == "POST" and action == "escalation" and escalation_form.is_valid():
        old_status = complaint.status
        escalation = escalation_form.save(commit=False)
        escalation.complaint = complaint
        escalation.escalated = True
        escalation.escalated_by = request.user
        escalation.save()
        complaint.status = Complaint.Status.ESCALATED
        complaint.save(update_fields=["status", "updated_at"])
        record_status_change(
            complaint,
            old_status,
            complaint.status,
            request.user,
            public_remarks="The complaint has been escalated for further action.",
            internal_remarks=escalation.remarks,
        )
        notify_complainant_for_status(complaint, complaint.status)
        log_activity(
            actor=request.user,
            complaint=complaint,
            action=ActivityLog.Action.ESCALATED,
            target=escalation,
            summary=f"Complaint '{complaint.title}' escalated to {escalation.escalated_to}.",
        )
        messages.success(request, "Complaint escalated.")
        return redirect(complaint.get_absolute_url())

    return render(
        request,
        "complaints/update_complaint.html",
        {
            "form": form,
            "complaint": complaint,
            "respondent": respondent,
            "respondent_form": respondent_form,
            "contact_form": contact_form,
            "response_form": response_form,
            "hearing_form": hearing_form,
            "attendance_form": attendance_form,
            "second_notice_form": second_notice_form,
            "escalation_form": escalation_form,
            "fee_form": fee_form,
            "latest_hearing": latest_hearing,
            "staff_assignment_options": get_staff_assignment_options(complaint) if request.user.is_barangay_admin else [],
            **workflow_context,
        },
    )


@login_required
@admin_required
def delete_complaint_view(request, pk):
    complaint = get_object_or_404(Complaint, pk=pk)
    if request.method == "POST":
        complaint.delete()
        messages.success(request, "Complaint deleted successfully.")
        return redirect("complaints:list")
    return render(request, "complaints/delete_complaint.html", {"complaint": complaint})


def get_report_complaints(request):
    date_from = parse_date(request.GET.get("date_from") or "")
    date_to = parse_date(request.GET.get("date_to") or "")
    complaints = Complaint.objects.select_related("category", "resident", "assigned_to")
    status = request.GET.get("status", "")
    priority = request.GET.get("priority", "")
    category = request.GET.get("category", "")
    assigned_to = request.GET.get("assigned_to", "")
    fee_status = request.GET.get("fee_status", "")
    sla_status = request.GET.get("sla_status", "")
    purok = request.GET.get("purok", "").strip()
    response_status = request.GET.get("response_status", "")
    mediation_result = request.GET.get("mediation_result", "")
    if date_from:
        complaints = complaints.filter(created_at__date__gte=date_from)
    if date_to:
        complaints = complaints.filter(created_at__date__lte=date_to)
    if status:
        complaints = complaints.filter(status=status)
    if priority:
        complaints = complaints.filter(priority=priority)
    if category:
        complaints = complaints.filter(category_id=category)
    if assigned_to:
        complaints = complaints.filter(assigned_to_id=assigned_to)
    if fee_status:
        complaints = complaints.filter(fee_status=fee_status)
    if purok:
        complaints = complaints.filter(Q(incident_location__icontains=purok) | Q(resident__resident_profile__purok__icontains=purok))
    if response_status:
        complaints = complaints.filter(respondent__response_status=response_status)
    if mediation_result:
        complaints = complaints.filter(hearings__mediation_result=mediation_result)
    if sla_status == "overdue":
        complaints = complaints.filter(deadline_at__lt=timezone.now()).exclude(
            status__in=[
                Complaint.Status.RESOLVED,
                Complaint.Status.UNRESOLVED,
                Complaint.Status.ESCALATED,
                Complaint.Status.CLOSED,
                Complaint.Status.REJECTED,
            ]
        )
    elif sla_status == "on_track":
        complaints = complaints.filter(deadline_at__gte=timezone.now()).exclude(
            status__in=[
                Complaint.Status.RESOLVED,
                Complaint.Status.UNRESOLVED,
                Complaint.Status.ESCALATED,
                Complaint.Status.CLOSED,
                Complaint.Status.REJECTED,
            ]
        )
    elif sla_status == "closed":
        complaints = complaints.filter(
            status__in=[
                Complaint.Status.RESOLVED,
                Complaint.Status.UNRESOLVED,
                Complaint.Status.ESCALATED,
                Complaint.Status.CLOSED,
                Complaint.Status.REJECTED,
            ]
        )
    return complaints.distinct(), date_from, date_to


def csv_safe_cell(value):
    if value is None:
        return ""
    text = str(value).replace("\r", " ").replace("\n", " ").strip()
    if text.startswith(("=", "+", "-", "@")):
        return f"'{text}"
    return text


def format_csv_date(value):
    if not value:
        return ""
    return timezone.localtime(value).strftime("%Y-%m-%d")


def format_csv_time(value):
    if not value:
        return ""
    return timezone.localtime(value).strftime("%I:%M %p")


def get_report_filter_summary(request):
    filters = []
    choice_filters = [
        ("status", "Status", dict(Complaint.Status.choices)),
        ("priority", "Priority", dict(Complaint.Priority.choices)),
        ("fee_status", "Fee Status", dict(Complaint.FeeStatus.choices)),
        ("response_status", "Respondent Response", dict(Respondent.ResponseStatus.choices)),
        ("mediation_result", "Mediation Result", dict(HearingMediation.MediationResult.choices)),
        ("sla_status", "SLA Status", {"overdue": "Overdue", "on_track": "On Track", "closed": "Closed"}),
    ]
    for key, label, choices in choice_filters:
        value = request.GET.get(key, "")
        if value:
            filters.append((label, choices.get(value, value)))

    category_id = request.GET.get("category", "")
    if category_id:
        category = ComplaintCategory.objects.filter(pk=category_id).first()
        filters.append(("Category", category.name if category else category_id))

    assigned_to_id = request.GET.get("assigned_to", "")
    if assigned_to_id:
        user = User.objects.filter(pk=assigned_to_id).first()
        filters.append(("Assigned To", user.get_full_name() or user.username if user else assigned_to_id))

    purok = request.GET.get("purok", "").strip()
    if purok:
        filters.append(("Purok / Location", purok))

    date_from = request.GET.get("date_from", "")
    if date_from:
        filters.append(("Date From", date_from))

    date_to = request.GET.get("date_to", "")
    if date_to:
        filters.append(("Date To", date_to))

    return filters


def format_report_pdf_date(value):
    if not value:
        return ""
    return timezone.localtime(value).strftime("%d-%b-%y")


def format_report_pdf_time(value):
    if not value:
        return ""
    return timezone.localtime(value).strftime("%I:%M %p")


def truncate_report_pdf_text(value, limit):
    text = " ".join(str(value or "").split())
    if len(text) <= limit:
        return text
    return f"{text[: max(limit - 1, 0)].rstrip()}..."


def build_report_pdf_seal(size=112):
    from PIL import Image as PILImage
    from PIL import ImageDraw, ImageFont

    image = PILImage.new("RGBA", (size, size), (255, 255, 255, 0))
    draw = ImageDraw.Draw(image)
    border = "#1E3A5F"
    inner_border = "#94A3B8"
    draw.ellipse((2, 2, size - 3, size - 3), fill="#FFFFFF", outline=border, width=4)
    draw.ellipse((14, 14, size - 15, size - 15), outline=inner_border, width=3)

    try:
        main_font = ImageFont.truetype("arialbd.ttf", size=32)
        sub_font = ImageFont.truetype("arial.ttf", size=14)
    except OSError:
        main_font = ImageFont.load_default()
        sub_font = ImageFont.load_default()

    top_text = "BARANGAY"
    bottom_text = "CAWITAN"
    top_box = draw.textbbox((0, 0), top_text, font=sub_font)
    bottom_box = draw.textbbox((0, 0), bottom_text, font=sub_font)
    main_box = draw.textbbox((0, 0), "BC", font=main_font)
    top_width = top_box[2] - top_box[0]
    bottom_width = bottom_box[2] - bottom_box[0]
    main_width = main_box[2] - main_box[0]
    main_height = main_box[3] - main_box[1]

    draw.text(((size - top_width) / 2, 18), top_text, fill=border, font=sub_font)
    draw.text(((size - main_width) / 2, (size - main_height) / 2 - 6), "BC", fill=border, font=main_font)
    draw.text(((size - bottom_width) / 2, size - 30), bottom_text, fill=border, font=sub_font)

    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)
    return buffer


@login_required
@admin_required
def reports_view(request):
    complaints, date_from, date_to = get_report_complaints(request)

    status_labels = dict(Complaint.Status.choices)
    by_status = [
        {**row, "label": status_labels.get(row["status"], row["status"])}
        for row in complaints.values("status").annotate(total=Count("id")).order_by("status")
    ]
    by_category = complaints.values("category__name").annotate(total=Count("id")).order_by("category__name")
    staff_workload = (
        User.objects.filter(role=User.Role.STAFF)
        .annotate(total_assigned=Count("assigned_complaints", filter=Q(assigned_complaints__in=complaints)))
        .order_by("last_name", "first_name")
    )
    staff_performance = []
    for person in staff_workload:
        assigned = complaints.filter(assigned_to=person)
        resolved = assigned.filter(status=Complaint.Status.RESOLVED)
        durations = [
            (item.resolved_at - item.created_at).total_seconds() / 3600
            for item in resolved
            if item.resolved_at
        ]
        active = assigned.filter(status__in=ACTIVE_ASSIGNMENT_STATUSES)
        staff_performance.append(
            {
                "user": person,
                "assigned": assigned.count(),
                "active": active.count(),
                "resolved": resolved.count(),
                "overdue": sum(1 for item in active if item.is_overdue),
                "average_resolution_hours": round(sum(durations) / len(durations), 1) if durations else 0,
            }
        )
    total_complaints = complaints.count()
    resolved_count = complaints.filter(status=Complaint.Status.RESOLVED).count()
    pending_count = complaints.filter(status=Complaint.Status.PENDING).count()
    overdue_count = sum(1 for complaint in complaints if complaint.is_overdue)
    resolved_with_duration = complaints.filter(resolved_at__isnull=False).annotate(
        resolution_duration=ExpressionWrapper(F("resolved_at") - F("created_at"), output_field=DurationField())
    )
    average_resolution = resolved_with_duration.aggregate(value=Avg("resolution_duration"))["value"]
    average_resolution_hours = round(average_resolution.total_seconds() / 3600, 1) if average_resolution else 0
    by_location = complaints.values("incident_location").annotate(total=Count("id")).order_by("-total")[:10]
    feedback_summary = ComplaintFeedback.objects.filter(complaint__in=complaints).aggregate(
        total=Count("id"),
        average_rating=Avg("rating"),
    )
    accepted_feedback_count = ComplaintFeedback.objects.filter(complaint__in=complaints, resolution_accepted=True).count()
    return render(
        request,
        "complaints/reports.html",
        {
            "by_status": by_status,
            "by_category": by_category,
            "staff_workload": staff_workload,
            "staff_performance": staff_performance,
            "total_complaints": total_complaints,
            "resolved_count": resolved_count,
            "pending_count": pending_count,
            "overdue_count": overdue_count,
            "average_resolution_hours": average_resolution_hours,
            "by_location": by_location,
            "date_from": request.GET.get("date_from", ""),
            "date_to": request.GET.get("date_to", ""),
            "query_string": request.GET.urlencode(),
            "status_choices": Complaint.Status.choices,
            "priority_choices": Complaint.Priority.choices,
            "fee_status_choices": Complaint.FeeStatus.choices,
            "category_choices": ComplaintCategory.objects.filter(is_active=True).order_by("name"),
            "staff_choices": User.objects.filter(role=User.Role.STAFF, is_active=True).order_by("last_name", "first_name"),
            "response_status_choices": Respondent.ResponseStatus.choices,
            "mediation_result_choices": HearingMediation.MediationResult.choices,
            "selected_status": request.GET.get("status", ""),
            "selected_priority": request.GET.get("priority", ""),
            "selected_category": request.GET.get("category", ""),
            "selected_assigned_to": request.GET.get("assigned_to", ""),
            "selected_fee_status": request.GET.get("fee_status", ""),
            "selected_sla_status": request.GET.get("sla_status", ""),
            "selected_purok": request.GET.get("purok", ""),
            "selected_response_status": request.GET.get("response_status", ""),
            "selected_mediation_result": request.GET.get("mediation_result", ""),
            "feedback_count": feedback_summary["total"] or 0,
            "average_feedback_rating": round(feedback_summary["average_rating"], 1) if feedback_summary["average_rating"] else 0,
            "accepted_feedback_count": accepted_feedback_count,
            "generated_at": timezone.localtime(timezone.now()),
            "generated_by": request.user.get_full_name() or request.user.username,
        },
    )


@login_required
@admin_required
def reports_export_xlsx_view(request):
    complaints, _, _ = get_report_complaints(request)
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    except ImportError:
        messages.error(request, "Excel export needs openpyxl. Install requirements.txt, then try again.")
        return redirect("complaints:reports")

    generated_at = timezone.localtime(timezone.now()).strftime("%B %d, %Y %I:%M %p")
    generated_by = request.user.get_full_name() or request.user.username
    total = complaints.count()
    resolved = complaints.filter(status=Complaint.Status.RESOLVED).count()
    overdue = sum(1 for complaint in complaints if complaint.is_overdue)

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Complaint Report"

    title_fill = PatternFill("solid", fgColor="D9EAF7")
    header_fill = PatternFill("solid", fgColor="2F4F7F")
    gray_fill = PatternFill("solid", fgColor="F2F2F2")
    green_fill = PatternFill("solid", fgColor="C6EFCE")
    orange_fill = PatternFill("solid", fgColor="FCE4D6")
    red_fill = PatternFill("solid", fgColor="FFC7CE")
    yellow_fill = PatternFill("solid", fgColor="FFF2CC")
    thin_border = Border(bottom=Side(style="thin", color="D9E2F3"))
    table_border = Border(
        left=Side(style="thin", color="D9E2F3"),
        right=Side(style="thin", color="D9E2F3"),
        top=Side(style="thin", color="D9E2F3"),
        bottom=Side(style="thin", color="D9E2F3"),
    )

    merged_header_rows = [
        ("Barangay Cawitan Official Complaint Monitoring Report", 1, 16, True),
        (BARANGAY_OFFICE_NAME, 2, 12, False),
        (f"Generated At: {generated_at}", 3, 11, False),
        (f"Generated By: {generated_by}", 4, 11, False),
    ]
    for value, row, size, bold in merged_header_rows:
        sheet.merge_cells(start_row=row, start_column=1, end_row=row, end_column=15)
        cell = sheet.cell(row=row, column=1, value=value)
        cell.fill = title_fill
        cell.font = Font(bold=bold, size=size, color="1F2937")
        cell.alignment = Alignment(horizontal="center", vertical="center")
        sheet.row_dimensions[row].height = 22

    summary_rows = [
        ("Total Complaints", total),
        ("Resolved", resolved),
        ("Overdue", overdue),
    ]
    for index, (label, value) in enumerate(summary_rows, start=6):
        sheet.cell(row=index, column=1, value=label)
        sheet.cell(row=index, column=2, value=value)
        for column in range(1, 3):
            cell = sheet.cell(row=index, column=column)
            cell.border = thin_border
            cell.alignment = Alignment(horizontal="left" if column == 1 else "center")
        sheet.cell(row=index, column=1).font = Font(bold=True)

    headers = [
        "Case No",
        "Title",
        "Category",
        "Priority",
        "Status",
        "Resident",
        "Assignee",
        "Location",
        "Created Date",
        "Created Time",
        "Deadline Date",
        "Deadline Time",
        "Resolved Date",
        "Resolved Time",
        "SLA Status",
    ]
    header_row = 10
    for column, label in enumerate(headers, start=1):
        cell = sheet.cell(row=header_row, column=column, value=label)
        cell.fill = header_fill
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = table_border

    sheet.freeze_panes = f"A{header_row + 1}"
    sheet.auto_filter.ref = f"A{header_row}:O{header_row}"

    text_columns = {1, 2, 3, 5, 6, 7, 8, 15}
    centered_columns = {4, 9, 10, 11, 12, 13, 14}
    for row, complaint in enumerate(complaints.order_by("-created_at"), start=header_row + 1):
        values = [
            f"CMP-{complaint.id:05d}",
            csv_safe_cell(complaint.title),
            csv_safe_cell(complaint.category.name if complaint.category else "Uncategorized"),
            complaint.get_priority_display(),
            complaint.get_status_display(),
            csv_safe_cell(complaint.resident.get_full_name() or complaint.resident.username),
            csv_safe_cell(complaint.assigned_to.get_full_name() or complaint.assigned_to.username if complaint.assigned_to else "Unassigned"),
            csv_safe_cell(complaint.incident_location),
            format_csv_date(complaint.created_at),
            format_csv_time(complaint.created_at),
            format_csv_date(complaint.deadline_at),
            format_csv_time(complaint.deadline_at),
            format_csv_date(complaint.resolved_at),
            format_csv_time(complaint.resolved_at),
            complaint.sla_label,
        ]
        for column, value in enumerate(values, start=1):
            cell = sheet.cell(row=row, column=column, value=value)
            cell.fill = gray_fill if row % 2 == 0 else PatternFill(fill_type=None)
            cell.border = table_border
            cell.alignment = Alignment(
                horizontal="center" if column in centered_columns else "left",
                vertical="center",
                wrap_text=column in text_columns,
            )

        status_cell = sheet.cell(row=row, column=5)
        status_value = str(status_cell.value).lower()
        if "resolved" in status_value or "closed" in status_value:
            status_cell.fill = green_fill
        elif complaint.is_overdue or "overdue" in str(complaint.sla_label).lower():
            status_cell.fill = red_fill
        elif "pending" in status_value:
            status_cell.fill = orange_fill

        priority_cell = sheet.cell(row=row, column=4)
        priority_value = str(priority_cell.value).lower()
        if priority_value == "urgent":
            priority_cell.fill = red_fill
        elif priority_value == "high":
            priority_cell.fill = orange_fill
        elif priority_value == "normal":
            priority_cell.fill = yellow_fill

    footer_row = header_row + total + 2
    sheet.merge_cells(start_row=footer_row, start_column=1, end_row=footer_row, end_column=15)
    footer_cell = sheet.cell(row=footer_row, column=1, value=BARANGAY_DOCUMENT_FOOTER)
    footer_cell.font = Font(italic=True, color="475569")
    footer_cell.alignment = Alignment(horizontal="center", vertical="center")
    footer_cell.fill = PatternFill("solid", fgColor="EAF1F8")

    widths = {
        "A": 14,
        "B": 30,
        "C": 22,
        "D": 14,
        "E": 24,
        "F": 25,
        "G": 25,
        "H": 30,
        "I": 15,
        "J": 15,
        "K": 15,
        "L": 15,
        "M": 15,
        "N": 15,
        "O": 16,
    }
    for column, width in widths.items():
        sheet.column_dimensions[column].width = width

    response = HttpResponse(
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
    response["Content-Disposition"] = 'attachment; filename="barangay-cawitan-official-complaints-report.xlsx"'
    workbook.save(response)
    return response


@login_required
@admin_required
def reports_export_pdf_view(request):
    complaints, _, _ = get_report_complaints(request)
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import HRFlowable, Image, LongTable, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
        from reportlab.pdfgen import canvas
    except ImportError:
        messages.error(request, "PDF export needs reportlab. Install requirements.txt, then try again.")
        return redirect("complaints:reports")

    class NumberedReportCanvas(canvas.Canvas):
        def __init__(self, *args, generated_label="", **kwargs):
            super().__init__(*args, **kwargs)
            self.generated_label = generated_label
            self._saved_page_states = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            self._saved_page_states.append(dict(self.__dict__))
            page_total = len(self._saved_page_states)
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self.draw_footer(page_total)
                canvas.Canvas.showPage(self)
            canvas.Canvas.save(self)

        def draw_footer(self, page_total):
            width, _ = landscape(A4)
            margin = 12 * mm
            self.setStrokeColor(colors.HexColor("#1E3A5F"))
            self.setLineWidth(0.8)
            self.line(margin, 10.8 * mm, width - margin, 10.8 * mm)
            self.setFillColor(colors.HexColor("#6B7280"))
            self.setFont("Helvetica-Oblique", 8)
            self.drawString(margin, 6.5 * mm, "Barangay Cawitan - Official Use Only")
            self.drawCentredString(width / 2, 6.5 * mm, f"Page {self._pageNumber} of {page_total}")
            self.drawRightString(width - margin, 6.5 * mm, self.generated_label)

    def priority_indicator(priority, style):
        palette = {
            "Urgent": "#DC2626",
            "High": "#F97316",
            "Normal": "#9CA3AF",
            "Low": "#9CA3AF",
        }
        dot_color = palette.get(str(priority), "#9CA3AF")
        return Paragraph(f'<font color="{dot_color}">&#9679;</font> {escape(str(priority))}', style)

    def status_text(status, sla_label, is_overdue, style):
        value = str(status)
        color = "#475569"
        if value == "Pending Review":
            color = "#F97316"
        elif value == "Second Notice Sent" or is_overdue or str(sla_label).lower() == "overdue":
            color = "#DC2626"
        elif value == "Resolved":
            color = "#16A34A"
        return Paragraph(f'<font color="{color}">{escape(value)}</font>', style)

    def sla_text(label, style):
        palette = {
            "On track": "#16A34A",
            "Closed": "#6B7280",
            "Overdue": "#DC2626",
        }
        return Paragraph(f'<font color="{palette.get(str(label), "#475569")}">{escape(str(label))}</font>', style)

    def row_priority_color(priority):
        if priority == "Urgent":
            return colors.HexColor("#DC2626")
        if priority == "High":
            return colors.HexColor("#F97316")
        return colors.HexColor("#D1D5DB")

    include_detail_pages = str(request.GET.get("includeDetailPages", "")).lower() in {"1", "true", "yes", "on"}
    overview_complaints = list(complaints.order_by("-created_at"))
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=14 * mm,
    )

    generated_by = request.user.get_full_name() or request.user.username
    generated_at = timezone.localtime(timezone.now())
    generated_at_label = generated_at.strftime("%B %d, %Y %I:%M %p")
    filters = get_report_filter_summary(request)
    total = len(overview_complaints)
    resolved = sum(1 for complaint in overview_complaints if complaint.status == Complaint.Status.RESOLVED)
    overdue = sum(1 for complaint in overview_complaints if complaint.is_overdue)
    filter_text = "; ".join(f"{label}: {value}" for label, value in filters) if filters else "None"
    styles = getSampleStyleSheet()
    title_color = colors.HexColor("#1E3A5F")
    muted = colors.HexColor("#555555")
    story = []

    letterhead_style = ParagraphStyle("Letterhead", parent=styles["Normal"], fontName="Helvetica", fontSize=9, leading=11, alignment=TA_CENTER, textColor=colors.HexColor("#334155"))
    barangay_style = ParagraphStyle("BarangayTitle", parent=letterhead_style, fontName="Helvetica-Bold", fontSize=16, leading=18, textColor=title_color)
    subtitle_style = ParagraphStyle("BarangaySubtitle", parent=letterhead_style, fontName="Helvetica-Oblique", fontSize=10, leading=12, textColor=muted)
    report_title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=18, leading=21, alignment=TA_CENTER, textColor=title_color)
    report_subtitle_style = ParagraphStyle("ReportSubtitle", parent=styles["Normal"], fontName="Helvetica", fontSize=10, leading=12, alignment=TA_CENTER, textColor=muted)
    meta_style_left = ParagraphStyle("MetaLeft", parent=styles["Normal"], fontName="Helvetica", fontSize=9, leading=11, alignment=TA_LEFT, textColor=colors.HexColor("#1F2937"))
    meta_style_right = ParagraphStyle("MetaRight", parent=meta_style_left, alignment=TA_RIGHT)
    stat_value_style = ParagraphStyle("StatValue", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=15, leading=17, alignment=TA_CENTER, textColor=title_color)
    stat_label_style = ParagraphStyle("StatLabel", parent=styles["Normal"], fontName="Helvetica", fontSize=8, leading=10, alignment=TA_CENTER, textColor=colors.HexColor("#475569"))
    table_header_style = ParagraphStyle("ReportTableHeader", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=9, leading=10, alignment=TA_CENTER, textColor=colors.white)
    cell_text_style = ParagraphStyle("ReportCell", parent=styles["Normal"], fontName="Helvetica", fontSize=8.5, leading=9, alignment=TA_LEFT, textColor=colors.HexColor("#0F172A"))
    detail_label_style = ParagraphStyle("DetailLabel", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=8.5, leading=10, textColor=title_color)
    detail_value_style = ParagraphStyle("DetailValue", parent=styles["Normal"], fontName="Helvetica", fontSize=8.5, leading=10, textColor=colors.HexColor("#1F2937"))
    detail_section_style = ParagraphStyle("DetailSection", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=11, leading=13, textColor=title_color)

    seal_image = Image(build_report_pdf_seal(), width=22 * mm, height=22 * mm)
    letterhead_copy = [
        Paragraph(escape(BARANGAY_DOCUMENT_HEADER[0]), letterhead_style),
        Paragraph(escape(BARANGAY_DOCUMENT_HEADER[1]), letterhead_style),
        Paragraph(escape(BARANGAY_DOCUMENT_HEADER[2]), letterhead_style),
        Paragraph(escape(BARANGAY_DOCUMENT_HEADER[3]), barangay_style),
        Paragraph(escape(BARANGAY_OFFICE_NAME), subtitle_style),
    ]
    story.append(Table([[seal_image, letterhead_copy]], colWidths=[26 * mm, document.width - (26 * mm)], style=TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("ALIGN", (0, 0), (0, 0), "CENTER"), ("ALIGN", (1, 0), (1, 0), "CENTER"), ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0), ("TOPPADDING", (0, 0), (-1, -1), 0), ("BOTTOMPADDING", (0, 0), (-1, -1), 0)])))
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=2, color=title_color, spaceBefore=0, spaceAfter=0))
    story.append(Spacer(1, 5 * mm))
    story.append(Table([[[Paragraph("OFFICIAL COMPLAINT MONITORING REPORT", report_title_style), Spacer(1, 1.5 * mm), Paragraph("Barangay Cawitan Complaint Summary and Case Register", report_subtitle_style)]]], colWidths=[document.width], style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F3F4F6")), ("LEFTPADDING", (0, 0), (-1, -1), 10), ("RIGHTPADDING", (0, 0), (-1, -1), 10), ("TOPPADDING", (0, 0), (-1, -1), 9), ("BOTTOMPADDING", (0, 0), (-1, -1), 9)])))
    story.append(Spacer(1, 4 * mm))
    story.append(Table([[Paragraph(f"<b>Generated:</b> {escape(generated_at_label)}", meta_style_left), Paragraph(f"<b>Generated by:</b> {escape(generated_by)}", meta_style_right)]], colWidths=[document.width / 2.0, document.width / 2.0], style=TableStyle([("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0), ("TOPPADDING", (0, 0), (-1, -1), 0), ("BOTTOMPADDING", (0, 0), (-1, -1), 0)])))
    story.append(Spacer(1, 3 * mm))
    story.append(Table([[Paragraph(f"<b>Total:</b> {total}", meta_style_left), Paragraph(f"<b>Resolved:</b> {resolved}", meta_style_left), Paragraph(f"<b>Overdue:</b> {overdue}", meta_style_left), Paragraph(f"<b>Filters:</b> {escape(filter_text)}", meta_style_left)]], colWidths=[22 * mm, 24 * mm, 23 * mm, document.width - 69 * mm], style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EFF6FF")), ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#BFDBFE")), ("LINEBEFORE", (1, 0), (-1, 0), 0.6, colors.HexColor("#BFDBFE")), ("LEFTPADDING", (0, 0), (-1, -1), 6), ("RIGHTPADDING", (0, 0), (-1, -1), 6), ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")])))
    story.append(Spacer(1, 4 * mm))
    story.append(Table([[ [Paragraph(str(value), stat_value_style), Spacer(1, 1 * mm), Paragraph(label, stat_label_style)] for value, label in ((total, "Total Complaints"), (resolved, "Resolved"), (overdue, "Overdue"), (len(filters), "Applied Filters")) ]], colWidths=[document.width / 4.0] * 4, style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#DBEAFE")), ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#BFDBFE")), ("INNERGRID", (0, 0), (-1, -1), 0.6, colors.HexColor("#BFDBFE")), ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 7), ("TOPPADDING", (0, 0), (-1, -1), 8), ("BOTTOMPADDING", (0, 0), (-1, -1), 8)])))
    story.append(Spacer(1, 5 * mm))

    table_data = [[Paragraph(escape(label), table_header_style) for label in ["Case No", "Title", "Category", "Priority", "Status", "Resident", "Assignee", "Location", "Filed Date", "Deadline Date", "SLA Status"]]]
    for complaint in overview_complaints:
        table_data.append([
            truncate_report_pdf_text(f"CMP-{complaint.id:05d}", 12),
            truncate_report_pdf_text(complaint.title, 32),
            truncate_report_pdf_text(complaint.category.name if complaint.category else "Uncategorized", 20),
            priority_indicator(complaint.get_priority_display(), cell_text_style),
            status_text(complaint.get_status_display(), complaint.sla_label, complaint.is_overdue, cell_text_style),
            truncate_report_pdf_text(complaint.resident.get_full_name() or complaint.resident.username, 22),
            truncate_report_pdf_text(complaint.assigned_to.get_full_name() or complaint.assigned_to.username if complaint.assigned_to else "Unassigned", 22),
            truncate_report_pdf_text(complaint.incident_location, 24),
            format_report_pdf_date(complaint.created_at),
            format_report_pdf_date(complaint.deadline_at),
            sla_text(complaint.sla_label, cell_text_style),
        ])

    report_table = LongTable(table_data, colWidths=[18 * mm, 35 * mm, 22 * mm, 18 * mm, 28 * mm, 25 * mm, 25 * mm, 28 * mm, 20 * mm, 22 * mm, 18 * mm], rowHeights=[10 * mm] * len(table_data), repeatRows=1)
    report_style_commands = [("BACKGROUND", (0, 0), (-1, 0), title_color), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("ALIGN", (0, 0), (-1, 0), "CENTER"), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4), ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 2), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, 0), 9), ("FONTNAME", (0, 1), (-1, -1), "Helvetica"), ("FONTSIZE", (0, 1), (-1, -1), 8.5), ("LINEBELOW", (0, 0), (-1, -1), 0.35, colors.HexColor("#E2E8F0")), ("LINEABOVE", (0, 0), (-1, 0), 0.35, title_color), ("ALIGN", (0, 1), (0, -1), "CENTER"), ("ALIGN", (8, 1), (10, -1), "CENTER")]
    for row_index, complaint in enumerate(overview_complaints, start=1):
        report_style_commands.append(("BACKGROUND", (0, row_index), (-1, row_index), colors.white if row_index % 2 else colors.HexColor("#F8FAFC")))
        report_style_commands.append(("LINEBEFORE", (0, row_index), (0, row_index), 3, row_priority_color(complaint.get_priority_display())))
    report_table.setStyle(TableStyle(report_style_commands))
    story.append(report_table)

    if include_detail_pages and overview_complaints:
        story.append(PageBreak())
        story.append(Paragraph("Full Case Detail", detail_section_style))
        story.append(Spacer(1, 3 * mm))
        for index, complaint in enumerate(overview_complaints):
            feedback = getattr(complaint, "feedback", None)
            comment_lines = []
            if feedback and feedback.comments:
                comment_lines.append(feedback.comments)
            if complaint.fee_notes:
                comment_lines.append(complaint.fee_notes)
            detail_rows = [
                ("Case No", f"CMP-{complaint.id:05d}"),
                ("Title", complaint.title),
                ("Category", complaint.category.name if complaint.category else "Uncategorized"),
                ("Priority", complaint.get_priority_display()),
                ("Status", complaint.get_status_display()),
                ("Resident", complaint.resident.get_full_name() or complaint.resident.username),
                ("Assignee", complaint.assigned_to.get_full_name() or complaint.assigned_to.username if complaint.assigned_to else "Unassigned"),
                ("Location", complaint.incident_location),
                ("Filed Date", format_report_pdf_date(complaint.created_at)),
                ("Created Time", format_report_pdf_time(complaint.created_at)),
                ("Deadline Date", format_report_pdf_date(complaint.deadline_at)),
                ("Deadline Time", format_report_pdf_time(complaint.deadline_at)),
                ("Resolved Date", format_report_pdf_date(complaint.resolved_at)),
                ("Resolved Time", format_report_pdf_time(complaint.resolved_at)),
                ("SLA Status", complaint.sla_label),
                ("Description", complaint.description or "-"),
                ("Public Remarks", complaint.public_remarks or "-"),
                ("Internal Remarks", complaint.internal_remarks or "-"),
                ("Second Notice Remarks", complaint.second_notice_remarks or "-"),
                ("Comments", " | ".join(comment_lines) if comment_lines else "-"),
            ]
            story.append(Table([[Paragraph(escape(label), detail_label_style), Paragraph(escape(" ".join(str(value or "").split())), detail_value_style)] for label, value in detail_rows], colWidths=[30 * mm, document.width - (30 * mm)], style=TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFF6FF")), ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")), ("LINEBELOW", (0, 0), (-1, -1), 0.35, colors.HexColor("#E2E8F0")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5), ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4)])))
            if index != len(overview_complaints) - 1:
                story.append(Spacer(1, 4 * mm))

    document.build(story, canvasmaker=lambda *args, **kwargs: NumberedReportCanvas(*args, generated_label=generated_at.strftime("%b %d, %Y"), **kwargs))
    buffer.seek(0)
    response = HttpResponse(buffer.getvalue(), content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="barangay-cawitan-official-complaints-report.pdf"'
    return response


@login_required
@admin_required
def category_management_view(request):
    categories = ComplaintCategory.objects.annotate(total_complaints=Count("complaint")).order_by("name")
    return render(request, "complaints/category_management.html", {"categories": categories})


@login_required
@admin_required
def category_create_view(request):
    form = ComplaintCategoryForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Category created successfully.")
        return redirect("complaints:categories")
    return render(request, "complaints/category_form.html", {"form": form, "category": None})


@login_required
@admin_required
def category_edit_view(request, pk):
    category = get_object_or_404(ComplaintCategory, pk=pk)
    form = ComplaintCategoryForm(request.POST or None, instance=category)
    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Category updated successfully.")
        return redirect("complaints:categories")
    return render(request, "complaints/category_form.html", {"form": form, "category": category})


@login_required
@admin_required
def category_toggle_view(request, pk):
    if request.method != "POST":
        return redirect("complaints:categories")
    category = get_object_or_404(ComplaintCategory, pk=pk)
    category.is_active = not category.is_active
    category.save(update_fields=["is_active"])
    messages.success(request, f"{category.name} has been {'activated' if category.is_active else 'deactivated'}.")
    return redirect("complaints:categories")
