# Generated by Django 4.2.30 on 2026-05-06 14:03

from django.db import migrations, models


def copy_legacy_valid_id_to_front(apps, schema_editor):
    ResidentProfile = apps.get_model("accounts", "ResidentProfile")
    for profile in ResidentProfile.objects.exclude(valid_id_image=""):
        if profile.valid_id_image and not profile.valid_id_front_image:
            profile.valid_id_front_image = profile.valid_id_image
            profile.save(update_fields=["valid_id_front_image"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resident_verification_otp_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='valid_id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='resident_ids/'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='valid_id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='resident_ids/'),
        ),
        migrations.RunPython(copy_legacy_valid_id_to_front, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='residentprofile',
            name='valid_id_image',
        ),
    ]
