# Generated by Django 4.2.30 on 2026-05-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_split_valid_id_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='valid_id_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('VOTERS_ID', "Voter's ID"), ('DRIVERS_LICENSE', "Driver's License"), ('PASSPORT', 'Passport'), ('UMID', 'UMID'), ('SSS_ID', 'SSS ID'), ('PHILHEALTH_ID', 'PhilHealth ID'), ('POSTAL_ID', 'Postal ID'), ('SENIOR_CITIZEN_ID', 'Senior Citizen ID'), ('PWD_ID', 'PWD ID'), ('STUDENT_ID', 'Student ID'), ('BARANGAY_ID', 'Barangay ID'), ('OTHER', 'Other government-issued ID')], max_length=30),
        ),
    ]
