# Generated by Codex privacy hardening pass

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_busy_staff_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("COMPLAINT_XLSX", "Complaint report Excel"),
                            ("COMPLAINT_PDF", "Complaint report PDF"),
                        ],
                        max_length=30,
                    ),
                ),
                ("purpose", models.CharField(max_length=80)),
                ("reason", models.TextField()),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("USED", "Used"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_data_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-requested_at"]},
        ),
    ]
