# Generated by Django 4.2 on 2026-04-24 02:05

import complaints.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintupdate',
            old_name='note',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='complaint_attachments/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reference_number',
            field=models.CharField(default=complaints.models.generate_reference_number, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='complaint_updates/'),
        ),
    ]
