# Generated by Django 4.2 on 2026-04-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_rename_note_complaintupdate_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
