# Generated by Django 4.2.30 on 2026-05-06 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0006_notification_delivery_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='internal_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='public_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='second_notice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='second_notice_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='second_notice_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='second_notice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaintresponse',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complaintresponse',
            name='source',
            field=models.CharField(choices=[('STAFF', 'Staff Remarks'), ('RESPONDENT', 'Respondent Response')], default='STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='complaintstatushistory',
            name='internal_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaintstatushistory',
            name='public_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDENT_NOT_CONTACTED', 'Respondent Not Contacted'), ('RESPONDENT_CONTACTED', 'Respondent Contacted'), ('WAITING_RESPONDENT_RESPONSE', 'Waiting for Respondent Response'), ('RESPONDENT_RESPONSE_RECORDED', 'Respondent Response Recorded'), ('NO_RESPONSE', 'No Response'), ('FAILED_TO_ATTEND', 'Failed to Attend'), ('SECOND_NOTICE_SENT', 'Second Notice Sent'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('IN_MEDIATION', 'In Mediation'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=40),
        ),
        migrations.AlterField(
            model_name='complaintresponse',
            name='status_after_response',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDENT_NOT_CONTACTED', 'Respondent Not Contacted'), ('RESPONDENT_CONTACTED', 'Respondent Contacted'), ('WAITING_RESPONDENT_RESPONSE', 'Waiting for Respondent Response'), ('RESPONDENT_RESPONSE_RECORDED', 'Respondent Response Recorded'), ('NO_RESPONSE', 'No Response'), ('FAILED_TO_ATTEND', 'Failed to Attend'), ('SECOND_NOTICE_SENT', 'Second Notice Sent'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('IN_MEDIATION', 'In Mediation'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], max_length=40),
        ),
        migrations.AlterField(
            model_name='complaintstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDENT_NOT_CONTACTED', 'Respondent Not Contacted'), ('RESPONDENT_CONTACTED', 'Respondent Contacted'), ('WAITING_RESPONDENT_RESPONSE', 'Waiting for Respondent Response'), ('RESPONDENT_RESPONSE_RECORDED', 'Respondent Response Recorded'), ('NO_RESPONSE', 'No Response'), ('FAILED_TO_ATTEND', 'Failed to Attend'), ('SECOND_NOTICE_SENT', 'Second Notice Sent'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('IN_MEDIATION', 'In Mediation'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], max_length=40),
        ),
        migrations.AlterField(
            model_name='complaintstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDENT_NOT_CONTACTED', 'Respondent Not Contacted'), ('RESPONDENT_CONTACTED', 'Respondent Contacted'), ('WAITING_RESPONDENT_RESPONSE', 'Waiting for Respondent Response'), ('RESPONDENT_RESPONSE_RECORDED', 'Respondent Response Recorded'), ('NO_RESPONSE', 'No Response'), ('FAILED_TO_ATTEND', 'Failed to Attend'), ('SECOND_NOTICE_SENT', 'Second Notice Sent'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('IN_MEDIATION', 'In Mediation'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], max_length=40),
        ),
        migrations.CreateModel(
            name='RespondentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='respondent_uploads/')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_evidence_files', to='complaints.complaint')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address or Purok')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_to_complainant', models.CharField(blank=True, max_length=100)),
                ('is_known_to_complainant', models.BooleanField(default=True)),
                ('identifying_details', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('contacted', models.BooleanField(default=False)),
                ('contact_method', models.CharField(blank=True, choices=[('CALL', 'Call'), ('SMS', 'SMS'), ('LETTER', 'Letter'), ('EMAIL', 'Email'), ('PERSONAL_NOTICE', 'Personal Notice'), ('OTHER', 'Other')], max_length=30)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_remarks', models.TextField(blank=True)),
                ('response_status', models.CharField(choices=[('WAITING', 'Waiting'), ('RESPONDED', 'Responded'), ('NO_RESPONSE', 'No Response'), ('FAILED_TO_ATTEND', 'Failed to Attend')], default='WAITING', max_length=30)),
                ('response_statement', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to='complaints.complaint')),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondent_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HearingMediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks or instructions')),
                ('complainant_attended', models.BooleanField(default=False)),
                ('respondent_attended', models.BooleanField(default=False)),
                ('attendance_recorded', models.BooleanField(default=False)),
                ('attendance_remarks', models.TextField(blank=True)),
                ('mediation_result', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('RESCHEDULED', 'Rescheduled'), ('FOR_ESCALATION', 'For Escalation')], default='PENDING', max_length=30)),
                ('agreement_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='complaints.complaint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalated', models.BooleanField(default=True)),
                ('escalation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('escalated_to', models.CharField(max_length=150)),
                ('reason', models.TextField(verbose_name='Reason for escalation')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation', to='complaints.complaint')),
                ('escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
