# Generated by Django 4.2.30 on 2026-05-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_notification_title_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='accuracy_certification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='privacy_consent',
            field=models.BooleanField(default=False),
        ),
    ]
