# Generated by Django 4.2.30 on 2026-05-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_categories_evidence_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sms_error',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sms_sent_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sms_status',
        ),
        migrations.AlterField(
            model_name='respondent',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('CALL', 'Call'), ('LETTER', 'Letter'), ('EMAIL', 'Email'), ('PERSONAL_NOTICE', 'Personal Notice'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
