# Generated by Django 4.2.30 on 2026-05-06 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0011_remove_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fee_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_complaint_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fee_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fee_paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fee_receipt_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fee_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='NOT_REQUIRED', max_length=20),
        ),
    ]
