# Generated by Django 4.2.30 on 2026-05-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0012_complaint_fee_amount_complaint_fee_collected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentevidence',
            name='review_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='respondentevidence',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('NEEDS_CLARIFICATION', 'Needs Clarification')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='respondentevidence',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondentevidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_respondent_evidence_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedevidence',
            name='review_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedevidence',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('NEEDS_CLARIFICATION', 'Needs Clarification')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadedevidence',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedevidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComplaintFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('resolution_accepted', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='complaints.complaint')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACCOUNT_UPDATED', 'Account Updated'), ('ACCOUNT_STATUS_CHANGED', 'Account Status Changed'), ('PASSWORD_RESET', 'Password Reset'), ('RESIDENT_VERIFIED', 'Resident Verified'), ('RESIDENT_VERIFICATION_UPDATED', 'Resident Verification Updated'), ('COMPLAINT_SUBMITTED', 'Complaint Submitted'), ('COMPLAINT_UPDATED', 'Complaint Updated'), ('ASSIGNMENT_CHANGED', 'Assignment Changed'), ('FEE_UPDATED', 'Fee Updated'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('EVIDENCE_REVIEWED', 'Evidence Reviewed'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('SECOND_NOTICE_RECORDED', 'Second Notice Recorded'), ('ESCALATED', 'Escalated'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted'), ('SLA_OVERDUE_FLAGGED', 'SLA Overdue Flagged'), ('NOTICE_GENERATED', 'Notice Generated')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
