# Generated by Django 4.2.30 on 2026-05-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_respondentevidence_review_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintfeedback',
            name='comments',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
