# Generated by Django 4.2.30 on 2026-05-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_complaintfeedback_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintcategory',
            name='responsible_department',
        ),
    ]
