# Generated by Codex privacy hardening pass

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0015_remove_complaintcategory_responsible_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_UPDATED", "Account Updated"),
                    ("ACCOUNT_STATUS_CHANGED", "Account Status Changed"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("RESIDENT_VERIFIED", "Resident Verified"),
                    ("RESIDENT_VERIFICATION_UPDATED", "Resident Verification Updated"),
                    ("COMPLAINT_SUBMITTED", "Complaint Submitted"),
                    ("COMPLAINT_UPDATED", "Complaint Updated"),
                    ("ASSIGNMENT_CHANGED", "Assignment Changed"),
                    ("FEE_UPDATED", "Fee Updated"),
                    ("EVIDENCE_UPLOADED", "Evidence Uploaded"),
                    ("EVIDENCE_REVIEWED", "Evidence Reviewed"),
                    ("HEARING_SCHEDULED", "Hearing Scheduled"),
                    ("SECOND_NOTICE_RECORDED", "Second Notice Recorded"),
                    ("ESCALATED", "Escalated"),
                    ("FEEDBACK_SUBMITTED", "Feedback Submitted"),
                    ("SLA_OVERDUE_FLAGGED", "SLA Overdue Flagged"),
                    ("NOTICE_GENERATED", "Notice Generated"),
                    ("RESIDENT_DIRECTORY_VIEWED", "Resident Directory Viewed"),
                    ("RESIDENT_PROFILE_VIEWED", "Resident Profile Viewed"),
                    ("DATA_EXPORT_REQUESTED", "Data Export Requested"),
                    ("DATA_EXPORT_APPROVED", "Data Export Approved"),
                    ("DATA_EXPORT_REJECTED", "Data Export Rejected"),
                    ("DATA_EXPORTED", "Data Exported"),
                    ("SENSITIVE_FILE_VIEWED", "Sensitive File Viewed"),
                ],
                max_length=40,
            ),
        ),
    ]
